# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath /home/mason/cs/code/vivado/thinpad_top/thinpad_top.cache/compile_simlib/modelsim
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.cache/wt [current_project]
set_property parent.project_path /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/bootr.coe
read_verilog {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_write_mask.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/per_defs.svh
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ex/id_ex.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/id.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/wb/mem_wb.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/mem/ex_mem.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_reg.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ex/ex.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/wb/hilo_reg.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/macro.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/except.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/except_defs.svh
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ctrl.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/if_id.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/pc/pc_reg.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/mem/mem.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/regfile.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_defs.svh
}
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_write_mask.sv]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/per_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ex/id_ex.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/id.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/wb/mem_wb.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/mem/ex_mem.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_reg.sv]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ex/ex.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/wb/hilo_reg.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/macro.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/except.sv]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/except_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/ctrl.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/if_id.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/pc/pc_reg.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/mem/mem.v]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/id/regfile.sv]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/cp0/cp0_defs.svh]
read_verilog -library xil_defaultlib -sv {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/bootrom.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/instance/cpu.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/bus/data_bus.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/flash.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/bus/inst_bus.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/sram.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/uart.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/imports/v_src/peripheral/vga_ctrl.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/new/thinpad_top.v
}
read_verilog -library xil_defaultlib {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/new/SEG7_LUT.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented/thinpad_top.srcs/sources_1/new/async.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/new/vga.v
}
read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/blk_mem_blockrom/blk_mem_blockrom.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/blk_mem_blockrom/blk_mem_blockrom_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_tx/fifo_uart_tx.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_tx/fifo_uart_tx.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_tx/fifo_uart_tx_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/pll_example/pll_example.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/pll_example/pll_example_board.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/pll_example/pll_example.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/constrs_1/new/thinpad_top.xdc
set_property used_in_implementation false [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/constrs_1/new/thinpad_top.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top thinpad_top -part xc7a100tfgg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef thinpad_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file thinpad_top_utilization_synth.rpt -pb thinpad_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
