# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo.xci
# IP: The module: 'tabn_axis_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo.xci
# IP: The module: 'tabn_axis_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/tabn_axis_fifo/tabn_axis_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tabn_axis_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
