`define IPV4_WIDTH 32
`define PORT_WIDTH 2
`define MAC_WIDTH 48

// routing
`define ROUTING_IPV4_START 32
`define ROUTING_IPV4_END 1
`define ROUTING_PORT_START 34
`define ROUTING_PORT_END 33
`define ROUTING_MASK_WIDTH 5
`define ROUTING_MASK_START 39
`define ROUTING_MASK_END 35
`define ROUTING_SON_START 53
`define ROUTING_SON_END 40
`define ROUTING_SON_NUM 16
`define ROUTING_BUCKET_INDEX_WIDTH 14
`define ROUTING_BUCKET_INDEX_COUNT 16384
`define ROUTING_TABLE_ENTRY_WIDTH 56

// arp
`define ARP_TABLE_ENTRY_WIDTH (`MAC_WIDTH + `IPV4_WIDTH)

// rram
// 125MHz -> 1ms = 125,000
`define RRAM_ADDR_WIDTH 11
`define TICK_PER_MS 125000
`define TIME_MS 0
`define ROUTING_TABLE_UPDATE_STATUS 8
`define ROUTING_TABLE_UPDATE_INSERT 12
`define ROUTING_TABLE_UPDATE_ITEM_NXTHOP 16
`define ROUTING_TABLE_UPDATE_ITEM_IP 20
`define ROUTING_TABLE_UPDATE_ITEM_PORT 24
`define ROUTING_TABLE_UPDATE_ITEM_MASK 28
`define TO_CPU_PACKET_STATUS 32
`define FROM_CPU_PACKET_STATUS 36
`define RRAM_CACHE_SIZE 40
`define TO_CPU_PACKET_LENGTH 64
`define TO_CPU_PACKET 68
`define FROM_CPU_PACKET_LENGTH 600
`define FROM_CPU_PACKET 604
