# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xci
# IP: The module: 'fifo_uart_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_rx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xci
# IP: The module: 'fifo_uart_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp9/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/fifo_uart_rx/fifo_uart_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
