@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Dec 06 11:52:01 +0800 2019
=======
REM Generated by Vivado on Fri Dec 06 09:18:57 +0800 2019
>>>>>>> 5db80c940b0e3f3a29847fa254a0ee156adf523e
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -view G:/cod19grp9/tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
