# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/eth_mac.xci
# IP: The module: 'eth_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/eth_mac.xci
# IP: The module: 'eth_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp2/Uncommented_old_verison/Uncommented_old_verison.srcs/sources_1/ip/eth_mac/synth/eth_mac_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
