# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom.xci
# IP: The module: 'blk_mem_ascii_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ascii_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom.xci
# IP: The module: 'blk_mem_ascii_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ascii_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
