# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/thinpad_top.xdc

# IP: ip/vgamem/vgamem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgamem || ORIG_REF_NAME==vgamem} -quiet] -quiet
