# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath /home/mason/cs/code/vivado/thinpad_top/thinpad_top.cache/compile_simlib/modelsim
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.cache/wt [current_project]
set_property parent.project_path /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented/thinpad_top.srcs/pic32.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented/thinpad_top.srcs/vr32.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/bootrom/bootrom_init.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vgamem/red.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented/thinpad_top.srcs/loader32.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/pic32.coe
read_verilog /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/defines.v
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/defines.v]
read_verilog -library xil_defaultlib {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/LLbit.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/SEG7_LUT.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/async.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/bootrom_controller.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/bus.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/cp0_reg.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/ctrl.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/div.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/ex.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/ex_mem.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/flash_controller.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/graphics_controller.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/hilo_reg.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/id.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/id_ex.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/if_id.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/mem.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/mem_wb.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/mips32.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/mmu_tlb.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/pc_reg.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/imports/cpu/regfile.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/serial.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/sram.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/vga.v
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/new/thinpad_top.v
}
read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vgamem/vgamem.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vgamem/vgamem_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/pll_example/pll_example.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/pll_example/pll_example_board.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/pll_example/pll_example.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/bootrom/bootrom.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/bootrom/bootrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/constrs_1/new/thinpad_top.xdc
set_property used_in_implementation false [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp10/Uncommented_old_version/Uncommented_old_version.srcs/constrs_1/new/thinpad_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
