# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/intomips_top.xdc

# IP: ip/blk_mem_graphics/blk_mem_graphics.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_graphics || ORIG_REF_NAME==blk_mem_graphics} -quiet] -quiet

# IP: ip/vga_clk_wiz/vga_clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_clk_wiz || ORIG_REF_NAME==vga_clk_wiz} -quiet] -quiet

# IP: ip/blk_mem_color/blk_mem_color.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_color || ORIG_REF_NAME==blk_mem_color} -quiet] -quiet
