# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath /home/mason/cs/code/vivado/thinpad_top/thinpad_top.cache/compile_simlib/modelsim
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.cache/wt [current_project]
set_property parent.project_path /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/bootrom.coe
add_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ascii_rom.coe
read_verilog {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/defines.svh
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/cpu_defines.svh
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/peripheral_defines.svh
}
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/defines.svh]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/cpu_defines.svh]
set_property file_type "Verilog Header" [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/peripheral_defines.svh]
read_verilog -library xil_defaultlib -sv {
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/sram_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/intomips_top.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/cpu.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/if/pc_reg.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/if/if_id.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/id/id.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/id/id_ex.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/ex/ex.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/ex/ex_mem.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/mem/mem.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/mem/mem_wb.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/registers.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/id/id_type.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/hilo.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/id/branch.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/flash_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/ctrl.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/cp0.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/mmu/mmu.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/serial_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/vga_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/ext_serial_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/mmu/tlb.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/cpu/mmu/tlb_lookup.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/async.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/bootrom_controller.sv
  /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/peripheral/usb_controller.sv
}
read_verilog -library xil_defaultlib /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented/src/util/seg7_lut.v
read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_graphics/blk_mem_graphics.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_graphics/blk_mem_graphics_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vga_clk_wiz/vga_clk_wiz.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vga_clk_wiz/vga_clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vga_clk_wiz/vga_clk_wiz.xdc]
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/vga_clk_wiz/vga_clk_wiz_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_color/blk_mem_color.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_color/blk_mem_color_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_ascii_rom/blk_mem_ascii_rom_ooc.xdc]

read_ip -quiet /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_bootrom/blk_mem_bootrom.xci
set_property used_in_implementation false [get_files -all /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/sources_1/ip/blk_mem_bootrom/blk_mem_bootrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/constrs_1/new/intomips_top.xdc
set_property used_in_implementation false [get_files /home/mason/Desktop/work/verilog-parser/tests/cod19grp7/Uncommented_old_version/Uncommented_old_version.srcs/constrs_1/new/intomips_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
